version: "3.8"

services:
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: eco-sort-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no

volumes:
  postgres_data:
