name: Build Flutter APK

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    # Step 3: Install Flutter dependencies
    - name: Install Flutter Dependencies
      run: flutter pub get
      working-directory: client


    # Step 4: Run Flutter build APK
    - name: Build APK
      run: flutter build apk --release
      working-directory: client

    # Step 5: Upload APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: client/build/app/outputs/flutter-apk/app-release.apk
